version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ressource"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: "development"
    labels:
      - "dependencies"
      - "securite"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "docker"
    directory: "/ressource"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "infra"
